name: hw-eliasfano
version: '0.1.0.1'
synopsis: Elias-Fano
description: Please see README.md
category: Data, Succinct Data Structures, Data Structures
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-eliasfano
homepage: http://github.com/haskell-works/hw-eliasfano#readme

extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base      >= 4          && < 5
- hw-bits   >= 0.4.0.0
- hw-int    >= 0.0.0.1
- hw-prim   >= 0.4.0.0
- safe
- vector

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.EliasFano
  - HaskellWorks.Data.FromListWord64
  - HaskellWorks.Data.ToListWord64
  dependencies:
  - hw-packed-vector  >= 0.0.0.1

tests:
  hw-eliasfano-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog
    - hspec
    - hw-eliasfano
    - hw-hedgehog
    - hw-hspec-hedgehog
    - hw-packed-vector
    - QuickCheck
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -msse4.2
    dependencies:
    - bytestring
    - criterion
    - hedgehog
    - hspec
    - hw-eliasfano
    - hw-hedgehog
    - hw-hspec-hedgehog
    - hw-packed-vector
    - hw-rankselect-base
    - hw-rankselect
    - mmap
    - QuickCheck
